name: update_requester
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  altfire_configurator: ^1.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  i18n:
    path: ../i18n/
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.1
  theme:
    path: ../theme/
  url_launcher: ^6.3.1
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.16.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
