name: db_client
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  # Because flutter_test depends on clock 1.1.1.
  clock: ^1.1.1
  drift: ^2.22.1
  drift_flutter: ^0.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.17.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  drift_dev: ^2.22.1
  test: ^1.25.12
