name: onepage
description: About One-page-only diary app
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  altfire_tracker: ^0.1.4
  custom_lint: ^0.6.5
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  riverpod_annotation: ^2.3.5

dev_dependencies:
  altive_lints: ^1.12.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

dependency_overrides:
  # Because Flutter Stable 3.24.1 is fixed to depend on collection 1.18.0,
  # override it with dependency_overrides to use a package that depends on collection 1.19.0.
  collection: ^1.19.0
  # Because firebase_core_web 2.17.4 depends on web ^0.5.1,
  # override it with dependency_overrides to use a package that depends on web ^1.0.0.
  web: ^1.0.0

flutter_gen:
  enabled: true
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
  assets:
    outputs:
      style: dot-delimiter

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Thin.ttf
          weight: 100