name: diary
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  db_client:
    path: ../db_client/
  flutter:
    sdk: flutter
  utils:
    path: ../utils/

dev_dependencies:
  altive_lints: ^1.16.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  mockito: ^5.4.4
  test: ^1.25.8
