name: ads
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  app_tracking_transparency: ^2.0.6
  flutter:
    sdk: flutter
  # google_mobile_ads: ^5.2.0

dev_dependencies:
  altive_lints: ^1.16.0
  custom_lint: ^0.7.0
  test: ^1.25.9
