name: theme
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.17.0
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
