include: package:altive_lints/altive_lints.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/l10n/*.dart"
    - "**/gen/*.dart"
    - "**/firebase_options_*.dart"
linter:
  rules: 
    specify_nonobvious_local_variable_types: false
