name: onepage
description: About One-page-only diary app
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  altfire_configurator: ^1.0.0
  altfire_tracker: ^0.1.5
  # Because flutter_test depends on clock 1.1.1.
  clock: ^1.1.1
  # Because flutter_test depends on collection 1.18.0.
  collection: ^1.18.0
  custom_lint: ^0.7.0
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.6.1
  hooks_riverpod: ^2.6.1
  i18n:
    path: ../i18n/
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.1
  riverpod_annotation: ^2.6.1
  scroll_calendar:
    path: ../scroll_calendar/
  theme:
    path: ../theme/
  update_requester:
    path: ../update_requester/
  url_launcher: ^6.3.1
  utils:
    path: ../utils/
  widgets:
    path: ../widgets/

dev_dependencies:
  altive_lints: ^1.16.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter_gen:
  enabled: true
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
  assets:
    outputs:
      style: dot-delimiter

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: packages/theme/fonts/NotoSansJP-Black.ttf
          weight: 900
        - asset: packages/theme/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: packages/theme/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: packages/theme/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: packages/theme/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: packages/theme/fonts/NotoSansJP-Thin.ttf
          weight: 100