name: scroll_calendar
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  # Because flutter_test depends on clock 1.1.1.
  clock: ^1.1.1
  flutter:
    sdk: flutter
  gap: ^3.0.1
  # Because flutter_localizations depends on intl 0.19.0.
  intl: ^0.19.0
  scrollable_positioned_list: ^0.3.8
  visibility_detector: ^0.4.0+2

dev_dependencies:
  altive_lints: ^1.17.0
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
